export const roles = [
  {
    id: 1,
    name: "ADMIN",
    description: "ADMIN role",
    permissions: [
      {
        id: 1,
        roleId: 1,
        permissionId: 1,
        permission: {
          id: 1,
          key: "users.create",
          name: "USERS CREATE",
          description: "Permission for users.create",
        },
      },
      {
        id: 2,
        roleId: 1,
        permissionId: 2,
        permission: {
          id: 2,
          key: "users.view",
          name: "USERS VIEW",
          description: "Permission for users.view",
        },
      },
      {
        id: 3,
        roleId: 1,
        permissionId: 3,
        permission: {
          id: 3,
          key: "users.update",
          name: "USERS UPDATE",
          description: "Permission for users.update",
        },
      },
      {
        id: 4,
        roleId: 1,
        permissionId: 4,
        permission: {
          id: 4,
          key: "users.delete",
          name: "USERS DELETE",
          description: "Permission for users.delete",
        },
      },
      {
        id: 5,
        roleId: 1,
        permissionId: 5,
        permission: {
          id: 5,
          key: "products.create",
          name: "PRODUCTS CREATE",
          description: "Permission for products.create",
        },
      },
      {
        id: 6,
        roleId: 1,
        permissionId: 6,
        permission: {
          id: 6,
          key: "products.view",
          name: "PRODUCTS VIEW",
          description: "Permission for products.view",
        },
      },
      {
        id: 7,
        roleId: 1,
        permissionId: 7,
        permission: {
          id: 7,
          key: "products.update",
          name: "PRODUCTS UPDATE",
          description: "Permission for products.update",
        },
      },
      {
        id: 8,
        roleId: 1,
        permissionId: 8,
        permission: {
          id: 8,
          key: "products.delete",
          name: "PRODUCTS DELETE",
          description: "Permission for products.delete",
        },
      },
      {
        id: 9,
        roleId: 1,
        permissionId: 9,
        permission: {
          id: 9,
          key: "customers.create",
          name: "CUSTOMERS CREATE",
          description: "Permission for customers.create",
        },
      },
      {
        id: 10,
        roleId: 1,
        permissionId: 10,
        permission: {
          id: 10,
          key: "customers.view",
          name: "CUSTOMERS VIEW",
          description: "Permission for customers.view",
        },
      },
      {
        id: 11,
        roleId: 1,
        permissionId: 11,
        permission: {
          id: 11,
          key: "customers.update",
          name: "CUSTOMERS UPDATE",
          description: "Permission for customers.update",
        },
      },
      {
        id: 12,
        roleId: 1,
        permissionId: 12,
        permission: {
          id: 12,
          key: "customers.delete",
          name: "CUSTOMERS DELETE",
          description: "Permission for customers.delete",
        },
      },
      {
        id: 13,
        roleId: 1,
        permissionId: 13,
        permission: {
          id: 13,
          key: "images.upload",
          name: "IMAGES UPLOAD",
          description: "Permission for images.upload",
        },
      },
      {
        id: 14,
        roleId: 1,
        permissionId: 14,
        permission: {
          id: 14,
          key: "images.delete",
          name: "IMAGES DELETE",
          description: "Permission for images.delete",
        },
      },
      {
        id: 15,
        roleId: 1,
        permissionId: 15,
        permission: {
          id: 15,
          key: "images.optimize",
          name: "IMAGES OPTIMIZE",
          description: "Permission for images.optimize",
        },
      },
      {
        id: 16,
        roleId: 1,
        permissionId: 16,
        permission: {
          id: 16,
          key: "addresses.create",
          name: "ADDRESSES CREATE",
          description: "Permission for addresses.create",
        },
      },
      {
        id: 17,
        roleId: 1,
        permissionId: 17,
        permission: {
          id: 17,
          key: "addresses.view",
          name: "ADDRESSES VIEW",
          description: "Permission for addresses.view",
        },
      },
      {
        id: 18,
        roleId: 1,
        permissionId: 18,
        permission: {
          id: 18,
          key: "addresses.update",
          name: "ADDRESSES UPDATE",
          description: "Permission for addresses.update",
        },
      },
      {
        id: 19,
        roleId: 1,
        permissionId: 19,
        permission: {
          id: 19,
          key: "addresses.delete",
          name: "ADDRESSES DELETE",
          description: "Permission for addresses.delete",
        },
      },
      {
        id: 20,
        roleId: 1,
        permissionId: 20,
        permission: {
          id: 20,
          key: "roles.manage",
          name: "ROLES MANAGE",
          description: "Permission for roles.manage",
        },
      },
    ],
    users: [
      {
        id: 2,
        userId: 2,
        roleId: 1,
        user: { id: 2, name: "Admin User", email: "admin@gmail.com" },
      },
      {
        id: 4,
        userId: 4,
        roleId: 1,
        user: {
          id: 4,
          name: "Alton Erdman",
          email: "elinore_murphy22@hotmail.com",
        },
      },
      {
        id: 5,
        userId: 5,
        roleId: 1,
        user: { id: 5, name: "Ira Berge", email: "cecile_hills@yahoo.com" },
      },
      {
        id: 8,
        userId: 8,
        roleId: 1,
        user: { id: 8, name: "Twahanur", email: "thohanur143@gmail.com" },
      },
    ],
  },
  {
    id: 2,
    name: "AGENT",
    description: "AGENT role",
    permissions: [
      {
        id: 21,
        roleId: 2,
        permissionId: 6,
        permission: {
          id: 6,
          key: "products.view",
          name: "PRODUCTS VIEW",
          description: "Permission for products.view",
        },
      },
      {
        id: 22,
        roleId: 2,
        permissionId: 5,
        permission: {
          id: 5,
          key: "products.create",
          name: "PRODUCTS CREATE",
          description: "Permission for products.create",
        },
      },
      {
        id: 23,
        roleId: 2,
        permissionId: 10,
        permission: {
          id: 10,
          key: "customers.view",
          name: "CUSTOMERS VIEW",
          description: "Permission for customers.view",
        },
      },
      {
        id: 24,
        roleId: 2,
        permissionId: 9,
        permission: {
          id: 9,
          key: "customers.create",
          name: "CUSTOMERS CREATE",
          description: "Permission for customers.create",
        },
      },
      {
        id: 25,
        roleId: 2,
        permissionId: 11,
        permission: {
          id: 11,
          key: "customers.update",
          name: "CUSTOMERS UPDATE",
          description: "Permission for customers.update",
        },
      },
      {
        id: 26,
        roleId: 2,
        permissionId: 13,
        permission: {
          id: 13,
          key: "images.upload",
          name: "IMAGES UPLOAD",
          description: "Permission for images.upload",
        },
      },
      {
        id: 27,
        roleId: 2,
        permissionId: 15,
        permission: {
          id: 15,
          key: "images.optimize",
          name: "IMAGES OPTIMIZE",
          description: "Permission for images.optimize",
        },
      },
      {
        id: 28,
        roleId: 2,
        permissionId: 17,
        permission: {
          id: 17,
          key: "addresses.view",
          name: "ADDRESSES VIEW",
          description: "Permission for addresses.view",
        },
      },
      {
        id: 29,
        roleId: 2,
        permissionId: 16,
        permission: {
          id: 16,
          key: "addresses.create",
          name: "ADDRESSES CREATE",
          description: "Permission for addresses.create",
        },
      },
      {
        id: 30,
        roleId: 2,
        permissionId: 18,
        permission: {
          id: 18,
          key: "addresses.update",
          name: "ADDRESSES UPDATE",
          description: "Permission for addresses.update",
        },
      },
    ],
    users: [
      {
        id: 3,
        userId: 3,
        roleId: 2,
        user: { id: 3, name: "Agent User", email: "agent@gmail.com" },
      },
      {
        id: 7,
        userId: 7,
        roleId: 2,
        user: {
          id: 7,
          name: "Nicolas Pollich",
          email: "armando_runte40@hotmail.com",
        },
      },
    ],
  },
  {
    id: 3,
    name: "INSPECTOR",
    description:
      "Inspector role with customer and product management permissions",
    permissions: [
      {
        id: 31,
        roleId: 3,
        permissionId: 10,
        permission: {
          id: 10,
          key: "customers.view",
          name: "CUSTOMERS VIEW",
          description: "Permission for customers.view",
        },
      },
      {
        id: 32,
        roleId: 3,
        permissionId: 11,

        permission: {
          id: 11,
          key: "customers.update",
          name: "CUSTOMERS UPDATE",
          description: "Permission for customers.update",
        },
      },
      {
        id: 33,
        roleId: 3,
        permissionId: 6,
        permission: {
          id: 6,
          key: "products.view",
          name: "PRODUCTS VIEW",
          description: "Permission for products.view",
        },
      },
      {
        id: 34,
        roleId: 3,
        permissionId: 5,
        permission: {
          id: 5,
          key: "products.create",
          name: "PRODUCTS CREATE",
          description: "Permission for products.create",
        },
      },
      {
        id: 35,
        roleId: 3,
        permissionId: 7,
        permission: {
          id: 7,
          key: "products.update",
          name: "PRODUCTS UPDATE",
          description: "Permission for products.update",
        },
      },
    ],
    users: [],
  },
];

export const allPermissions = [
  {
    id: "16",
    key: "addresses.create",
    name: "ADDRESSES CREATE",
    description: "Permission for addresses.create",
  },
  {
    id: "19",
    key: "addresses.delete",
    name: "ADDRESSES DELETE",
    description: "Permission for addresses.delete",
  },
  {
    id: "18",
    key: "addresses.update",
    name: "ADDRESSES UPDATE",
    description: "Permission for addresses.update",
  },
  {
    id: "17",
    key: "addresses.view",
    name: "ADDRESSES VIEW",
    description: "Permission for addresses.view",
  },
  {
    id: "9",
    key: "customers.create",
    name: "CUSTOMERS CREATE",
    description: "Permission for customers.create",
  },
  {
    id: "12",
    key: "customers.delete",
    name: "CUSTOMERS DELETE",
    description: "Permission for customers.delete",
  },
  {
    id: "11",
    key: "customers.update",
    name: "CUSTOMERS UPDATE",
    description: "Permission for customers.update",
  },
  {
    id: "10",
    key: "customers.view",
    name: "CUSTOMERS VIEW",
    description: "Permission for customers.view",
  },
  {
    id: "14",
    key: "images.delete",
    name: "IMAGES DELETE",
    description: "Permission for images.delete",
  },
  {
    id: "15",
    key: "images.optimize",
    name: "IMAGES OPTIMIZE",
    description: "Permission for images.optimize",
  },
  {
    id: "13",
    key: "images.upload",
    name: "IMAGES UPLOAD",
    description: "Permission for images.upload",
  },
  {
    id: "5",
    key: "products.create",
    name: "PRODUCTS CREATE",
    description: "Permission for products.create",
  },
  {
    id: "8",
    key: "products.delete",
    name: "PRODUCTS DELETE",
    description: "Permission for products.delete",
  },
  {
    id: "7",
    key: "products.update",
    name: "PRODUCTS UPDATE",
    description: "Permission for products.update",
  },
  {
    id: "6",
    key: "products.view",
    name: "PRODUCTS VIEW",
    description: "Permission for products.view",
  },
  {
    id: "20",
    key: "roles.manage",
    name: "ROLES MANAGE",
    description: "Permission for roles.manage",
  },
  {
    id: "1",
    key: "users.create",
    name: "USERS CREATE",
    description: "Permission for users.create",
  },
  {
    id: "4",
    key: "users.delete",
    name: "USERS DELETE",
    description: "Permission for users.delete",
  },
  {
    id: "3",
    key: "users.update",
    name: "USERS UPDATE",
    description: "Permission for users.update",
  },
  {
    id: "2",
    key: "users.view",
    name: "USERS VIEW",
    description: "Permission for users.view",
  },
];
