import { AppSidebar } from "@/components/pages/shared/sidebar/app-sidebar";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar";
import { BellDotIcon, SunIcon } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider>
          <AppSidebar />
          <SidebarInset>
            <header className="sticky top-0 z-999 flex border-b h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 bg-background">
              <div className="w-full flex items-center justify-between gap-2 px-4">
                <SidebarTrigger className="-ml-1" />
                <div className="w-full flex items-center justify-between gap-2">
                  <div className="flex flex-col items-start">
                    <span className="text-xs text-muted-foreground/80">Good afternoon</span>
                    <span className="text-lg font-semibold text-foreground">Welcome back, Bishal</span>
                  </div>
                  <div className="flex items-center gap-4">
                    <div>
                      <SunIcon className="w-6 h-6" />
                    </div>
                    <div className="relative group">
                      <button className="relative p-2 rounded-full hover:bg-accent hover:text-accent-foreground transition-colors">
                        <BellDotIcon className="w-6 h-6" />
                        <span className="absolute -top-1 -right-1 flex h-5 w-5 items-center justify-center rounded-full bg-destructive text-white text-[10px] font-bold text-destructive-foreground shadow">
                          3
                        </span>
                      </button>
                      {/* Optional: subtle pulse animation on the badge */}
                      <span className="absolute -top-1 -right-1 flex h-5 w-5">
                        <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-destructive opacity-75"></span>
                      </span>
                    </div>
                    <div>
                      <div className="relative group">
                        <button className="flex items-center gap-3 rounded-full pl-2 pr-4 py-2 text-sm font-medium text-foreground/80 hover:bg-accent/50 hover:text-foreground transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 focus:ring-offset-background">
                          <Avatar className="w-9 h-9 ring-2 ring-offset-2 ring-offset-background ring-primary/20">
                            <AvatarImage src="https://github.com/shadcn.png" />
                            <AvatarFallback className="bg-linear-to-br from-primary/20 to-primary/40 text-primary-foreground">
                              BI
                            </AvatarFallback>
                          </Avatar>
                          <div className="hidden md:flex flex-col items-start">
                            <span className="text-sm font-semibold text-foreground">
                              Bishal
                            </span>
                            <span className="text-xs text-muted-foreground/70">
                              Developer
                            </span>
                          </div>
                        </button>

                        {/* Dropdown Menu */}
                        <div className="absolute right-0 mt-2 w-56 origin-top-right rounded-xl border bg-popover shadow-lg ring-1 ring-black/5 focus:outline-none opacity-0 invisible group-hover:opacity-100 group-hover:visible transition-all duration-200">
                          <div className="p-2">
                            <div className="flex items-center gap-3 px-2 py-2">
                              <Avatar className="w-10 h-10">
                                <AvatarImage src="https://github.com/shadcn.png" />
                                <AvatarFallback>BI</AvatarFallback>
                              </Avatar>
                              <div>
                                <p className="text-sm font-semibold">Bishal</p>
                                <p className="text-xs text-muted-foreground">
                                  bishal@example.com
                                </p>
                              </div>
                            </div>
                            <hr className="my-2" />
                            <a
                              href="/profile"
                              className="flex items-center gap-2 rounded-md px-2 py-2 text-sm hover:bg-accent hover:text-accent-foreground transition-colors"
                            >
                              Profile
                            </a>
                            <a
                              href="/settings"
                              className="flex items-center gap-2 rounded-md px-2 py-2 text-sm hover:bg-accent hover:text-accent-foreground transition-colors"
                            >
                              Settings
                            </a>
                            <hr className="my-2" />
                            <button className="flex w-full items-center gap-2 rounded-md px-2 py-2 text-sm hover:bg-accent hover:text-accent-foreground transition-colors">
                              Log out
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </header>
            <div className="flex flex-1 flex-col gap-4 pt-0">
              {children}
              <div className="bg-muted/50 min-h-screen flex-1 rounded-xl md:min-h-min" />
            </div>
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}
